(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},e="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ba(a,b){if(b){var c=e;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ba("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});function ca(){ca=function(){};e.Symbol||(e.Symbol=da)}var ea=0;function da(a){return"jscomp_symbol_"+(a||"")+ea++}
function fa(){ca();var a=e.Symbol.iterator;a||(a=e.Symbol.iterator=e.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ga(this)}});fa=function(){}}function ga(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){fa();a={next:a};a[e.Symbol.iterator]=function(){return this};return a}
ba("Array.from",function(a){return a?a:function(a,c,d){fa();c=c?c:function(a){return a};var f=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)f.push(c.call(d,g.value));else for(var g=a.length,h=0;h<g;h++)f.push(c.call(d,a[h]));return f}});
function ia(a,b){fa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ba("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(a){return a})}});
ba("Array.prototype.fill",function(a){return a?a:function(a,c,d){var f=this.length||0;0>c&&(c=Math.max(0,f+c));if(null==d||d>f)d=f;d=Number(d);0>d&&(d=Math.max(0,f+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",
arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",
copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn vec2(dot(a,b),dot(a,vec2(-b.y,b.x)))/dot(b,b);\n}\n",divfc:"vec2 divfc(float a,vec2 b){\nreturn a*vec2(b.x,-b.y)/dot(b,b);\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",
green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",
logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(dot(a,vec2(b.x,-b.y)),dot(a,b.yx));\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",
random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",
sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\nprecision highp int;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",
subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var na=!1,k,m,n,r,v=!1,oa,w=!1,pa=1;
function qa(){function a(c){k.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!na){k=document.createElement("canvas");k.id="glcanvas";k.style.display="none";k.width=k.height=0;document.body.appendChild(k);m=document.createElement("canvas");m.id="tmpcanvas";m.style.display="none";m.width=m.height=0;document.body.appendChild(m);var b="Unknown";k.addEventListener("webglcontextcreationerror",a,!1);(n=k.getContext("webgl"))||(n=k.getContext("experimental-webgl"));
if(!n)throw new ra("Could not obtain a WebGL context.\nReason: "+b);k.removeEventListener("webglcontextcreationerror",a,!1);w=n.getExtension("OES_texture_float")&&n.getExtension("OES_texture_float_linear");w||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(v=(oa=n.getExtension("OES_texture_half_float"))&&n.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),w=v=!1,n.getExtension("OES_texture_half_float")&&n.getExtension("OES_texture_half_float_linear")&&n.getExtension("EXT_color_buffer_half_float")?v=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures."));na=!0}};function sa(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,d=a.length;c<d;c++)b[c]=sa(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=sa(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function ta(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,d=a.length;c<d;c++)if(!ta(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(d=0;d<c.length;d++){var f=c[d];if(!ta(a[f],b[f]))return!1}return!0}return!1}function y(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function z(a){if("boolean"===a.ctype)return A.C;if("number"===a.ctype)return a=a.value,1E-5>Math.abs(a.imag)?(a.real|0)===a.real?A.A:A.f:A.h;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=z(b[0]),d=1;d<b.length;d++)c=B(c,z(b[d]));if(c)return{type:"list",length:b.length,i:c}}}else if("string"===a.ctype||"image"===a.ctype)return A.image;console.error("Cannot guess type of the following type:");console.log(a);return!1}var ua=0;function D(){ua++;return"_h"+ua}
function va(a,b){if(a>k.width||b>k.height)k.width=Math.ceil(a),k.height=Math.ceil(b)}function wa(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function xa(a){return wa(a,0,a.instance.canvas.clientHeight)}function ya(a){return wa(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}var za=new Float32Array(1),Aa=new Int32Array(za.buffer);
function Ba(a){za[0]=a;a=Aa[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Ca(a){if(w)return new Float32Array(a);if(v){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=Ba(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Da(a){return w?new Float32Array(a):v?new Uint16Array(a):new Uint8Array(a)}function Ea(){return w?n.FLOAT:v?oa.HALF_FLOAT_OES:n.UNSIGNED_BYTE}
function Fa(a){for(var b=[],c=0;c<a.length;c++)if(w)b.push(a[c]);else if(v){var d=a[c],f=(d&31744)>>10,g=d&1023;b.push((d>>15?-1:1)*(f?31===f?g?NaN:Infinity:Math.pow(2,f-15)*(1+g/1024):g/1024*6.103515625E-5))}else b.push(a[c]/255);return b}function Ga(a){for(var b=1;b<a;)b<<=1;return b};function Ha(a,b){a.hasOwnProperty("readcanvaswrappers")||(a.readcanvaswrappers=Array(4));var c=2*b.U+b.aa;a.readcanvaswrappers.hasOwnProperty(c)||(a.writecanvaswrapper&&a.writecanvaswrapper.generation>a.generation&&a.writecanvaswrapper.ma(),a.readcanvaswrappers[c]=new E(a,b),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.readcanvaswrappers[c].generation+1)})));a.writecanvaswrapper&&(a.writecanvaswrapper=a.readcanvaswrappers[c]);
return a.readcanvaswrappers[c]}function Ia(a){if(!a.hasOwnProperty("writecanvaswrapper")){var b=-1;if(a.readcanvaswrappers)for(var c=3;0<=c;c--)a.readcanvaswrappers.hasOwnProperty(b)&&(b=c);else a.readcanvaswrappers=Array(4);-1==b&&(c={aa:!0,U:!1,repeat:!1},b=2*c.U+c.aa,a.readcanvaswrappers[b]=new E(a,c));a.writecanvaswrapper=a.readcanvaswrappers[b]}a.readPixels=a.writecanvaswrapper.readPixels.bind(a.writecanvaswrapper);return a.writecanvaswrapper}
function E(a,b){this.canvas=a;this.S=b;this.K=a.width;this.G=a.height;Ja(this);this.l=0;this.s=[];this.ca=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.readPixels=this.readPixels.bind(this);a.cdyUpdate=this.ma.bind(this);a=Da(this.Y*this.L*4);for(var c=0;2>c;c++)this.s[c]=n.createTexture(),n.bindTexture(n.TEXTURE_2D,this.s[c]),n.pixelStorei(n.UNPACK_ALIGNMENT,1),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,this.Y,this.L,0,n.RGBA,Ea(),a),b.U?n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,
b.aa?n.LINEAR_MIPMAP_LINEAR:n.NEAREST_MIPMAP_LINEAR):n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.aa?n.LINEAR:n.NEAREST),n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MAG_FILTER,b.aa?n.LINEAR:n.NEAREST),this.ca[c]=n.createFramebuffer(),n.bindFramebuffer(n.FRAMEBUFFER,this.ca[c]),n.framebufferTexture2D(n.FRAMEBUFFER,n.COLOR_ATTACHMENT0,n.TEXTURE_2D,this.s[c],0);this.ba=new Ka(ja.copytexture_v,ja.copytexture_f);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,
1,0,1,1,0]);a=n.getAttribLocation(this.ba.l,"aPos");n.enableVertexAttribArray(a);c=n.getAttribLocation(this.ba.l,"aTexCoord");n.enableVertexAttribArray(c);var d=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;n.bufferData(n.ARRAY_BUFFER,f+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,0,b);n.bufferSubData(n.ARRAY_BUFFER,f,d);n.vertexAttribPointer(a,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(c,2,n.FLOAT,!1,0,f)}
function Ja(a){a.Y=Ga(a.K+a.K/2*(a.S.U&&a.S.repeat));a.L=Ga(a.G+a.G/2*(a.S.U&&a.S.repeat))}E.prototype.bindTexture=function(){n.bindTexture(n.TEXTURE_2D,this.s[this.l])};E.prototype.bindFramebuffer=function(){n.bindFramebuffer(n.FRAMEBUFFER,this.ca[this.l^1]);this.l^=1};
E.prototype.ma=function(){var a;this.canvas.img.hasOwnProperty("getContext")?a=this.canvas.img.getContext("2d"):(this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.K,this.canvas.img.height=this.G,a=this.canvas.img.getContext("2d"));a.clearRect(0,0,this.K,this.G);this.drawTo(a,0,0);this.canvas.img.generation++};
function La(a){if(a.canvas.live||a.canvas.ready&&!(a.generation>=a.canvas.generation)){if(a.K!=a.canvas.width||a.G!=a.canvas.height){a.K=a.canvas.width;a.G=a.canvas.height;Ja(a);for(var b=Da(a.Y*a.L*4),c=0;2>c;c++)n.bindTexture(n.TEXTURE_2D,a.s[c]),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,a.Y,a.L,0,n.RGBA,Ea(),b)}a.bindTexture();n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,1);a.S.repeat?(m.width=a.Y,m.height=a.L,b=m.getContext("2d"),b.drawImage(a.canvas.img,0,a.L-a.G),b.drawImage(a.canvas.img,a.K,a.L-a.G),b.drawImage(a.canvas.img,
0,a.L-2*a.G),b.drawImage(a.canvas.img,a.K,a.L-2*a.G),n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Ea(),m)):n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Ea(),a.canvas.img);a.S.U&&n.generateMipmap(n.TEXTURE_2D);n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,0);a.generation=a.canvas.generation;console.log("Image has been loaded to GPU")}}
E.prototype.drawTo=function(a,b,c){va(this.K,this.G);n.viewport(0,0,this.Y,this.L);n.useProgram(this.ba.l);n.activeTexture(n.TEXTURE0);n.bindTexture(n.TEXTURE_2D,this.s[this.l]);this.ba.s.sampler([0]);n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();a.drawImage(k,0,k.height-this.G,this.K,this.G,b,c,this.K,this.G)};
E.prototype.readPixels=function(a,b,c,d){n.bindFramebuffer(n.FRAMEBUFFER,this.ca[this.l]);n.framebufferTexture2D(n.FRAMEBUFFER,n.COLOR_ATTACHMENT0,n.TEXTURE_2D,this.s[this.l],0);var f=Da(c*d*4);n.readPixels(a,this.G-b-d,c,d,n.RGBA,Ea(),f);a=[];for(--d;0<=d;d--)a=a.concat(Fa(f.slice(d*c*4,(d+1)*c*4)));return a};function Ma(a,b){this.B=a;this.S=b;Na(this)}
function Na(a){var b=Oa(new Pa(a.B),a.S);a.s=b.D;a.F=b.F;a.ia=b.ia;a.ba=ja.standardFragmentHeader+b.code;a.ca=ja.vshader;a.l=new Ka(a.ca,a.ba);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);var b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),c=n.getAttribLocation(a.l.l,"aPos");n.enableVertexAttribArray(c);a=n.getAttribLocation(a.l.l,"aTexCoord");n.enableVertexAttribArray(a);var d=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;n.bufferData(n.ARRAY_BUFFER,f+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,
0,b);n.bufferSubData(n.ARRAY_BUFFER,f,d);n.vertexAttribPointer(c,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(a,2,n.FLOAT,!1,0,f)}
function Qa(a){function b(a,c,d){if(a)if("function"===typeof a)switch(c){case A.h:a([d.value.real,d.value.imag]);break;case A.C:d.value?a([1]):a([0]);break;case A.A:case A.f:a([d.value.real]);break;default:if("list"===c.type&&c.i===A.f)a(d.value.map(function(a){return a.value.real}));else if("list"===c.type&&"list"===c.i.type&&c.i.i===A.f){for(var f=[],q=0;q<c.length;q++)for(var t=0;t<c.i.length;t++)f.push(d.value[q].value[t].value.real);a(f)}else console.error("Don't know how to set uniform of type "+
F(c)+", to "+d)}else if("list"===c.type)if(q=Ra(c),1===G(c)&&q===A.f){c=Sa(c.length);var u=0;for(f in c)b(a["a"+f],A.da(c[f]),{ctype:"list",value:H(c[f]).map(function(a){return d.value[u+a]})}),u+=c[f]}else for(f=0;f<c.length;f++)b(a["a"+f],c.i,{ctype:"list",value:d.value[f].value});else console.error("Don't know how to set uniform of type "+F(c)+", to"),console.log(d)}for(var c in a.s){var d=a.B.evaluateAndVal(a.s[c].W),f=a.s[c].type;if(!I(Ta(d),f)){console.log("Type of "+c+" changed ("+F(Ta(d))+
" is no subtype of  "+F(f)+"); forcing rebuild.");Na(a);n.useProgram(a.l.l);Qa(a);return}a.l.s[c]&&b(a.l.s[c],f,d)}[["rnd_",function(){return[Math.random()]}],["_lowerleft",function(){var b=xa(a.B);return[b.x,b.y]}],["_lowerright",function(){var b=ya(a.B);return[b.x,b.y]}]].map(function(b){return a.l.s[b[0]]&&a.l.s[b[0]](b[1]())})}
function Ua(a){var b=0,c;for(c in a.F)for(var d in a.F[c]){n.activeTexture(n.TEXTURE0+b);var f=a.F[c][d],g=f.name,h={aa:f.X.hasOwnProperty("interpolate")?f.B.evaluateAndVal(f.X.interpolate).value:!0,U:f.X.hasOwnProperty("mipmap")?f.B.evaluateAndVal(f.X.mipmap).value:!1,repeat:f.X.hasOwnProperty("repeat")?f.B.evaluateAndVal(f.X.repeat).value:!1},f=Va(f,h);La(f);f.bindTexture();[["_sampler"+g,[b]],["_ratio"+g,[f.K/f.G]],["_cropfact"+g,[f.K/f.Y,f.G/f.L]],["_repeat"+g,[h.repeat]],["_mipmap"+g,[h.U]]].map(function(b){return a.l.s[b[0]]&&
a.l.s[b[0]](b[1])});b++}};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,d,f,g,h,l){if(!b.oa||b.na<pa)b.oa=!0,b.na=pa,b.qa=new Ma(a,b);b=b.qa;var p;a:{for(p in b.ia)if(b.B.getMyfunction(p).generation>b.ia[p]){console.log(p+" is outdated; forcing rebuild.");p=!1;break a}p=!0}p||Na(b);var q=h/g;p=d.x+-(f.y-d.y)*q;q=d.y+(f.x-d.x)*q;va(g,h);l?n.viewport(0,0,g,h):n.viewport(0,k.height-h,g,h);n.useProgram(b.l.l);Qa(b);d=[f.x-d.x,p-d.x,d.x,f.y-d.y,q-d.y,d.y,0,0,1];b.l.s.hasOwnProperty("transformMatrix")&&b.l.s.transformMatrix([d[0],
d[3],d[6],d[1],d[4],d[7],d[2],d[5],d[8]]);Ua(b);l?(l.bindFramebuffer(),l.generation=++l.canvas.generation):n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();l&&(l.generation=Math.max(l.generation,l.canvas.generation+1))}r=a.nada;a.defineFunction("compile",1,function(b){b=Oa(new Pa(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){pa++;return r});a.defineFunction("colorplot",1,function(c){qa();var d=a.instance.canvas.clientWidth,
f=a.instance.canvas.clientHeight,g=a.instance.canvas.width,h=a.instance.canvas.height;b(c[0],xa(a),ya(a),g,h,null);a.instance.canvas.getContext("2d").drawImage(k,0,0,g,h,0,0,d,f);return r});a.defineFunction("colorplot",3,function(c){qa();var d=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),h={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},l={x:Math.max(f.x,g.x),y:Math.min(f.y,g.y)};c=a.instance.canvas.clientWidth;var p=a.instance.canvas.clientHeight,q=a.instance.canvas.width,
t=a.instance.canvas.height,u=wa(a,0,0),x=xa(a),C=ya(a),C=Math.abs((f.x-g.x)/(x.x-C.x)),u=Math.abs((f.y-g.y)/(u.y-x.y));b(d,h,l,q*C,t*u,null);d=a.instance.canvas.getContext("2d");h=Math.min(f.x,g.x);f=Math.max(f.y,g.y);g=a.getInitialMatrix();d.drawImage(k,0,0,q*C,t*u,h*g.a-f*g.b+g.tx,h*g.c-f*g.d-g.ty,C*c,u*p);return r});a.defineFunction("colorplot",4,function(c){qa();var d=a.extractPoint(a.evaluateAndVal(c[0])),f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!d.ok||!f.ok||
"string"!==g.ctype)return r;var g=a.getImage(g.value,!0),h=Ia(g);b(c,d,f,g.width,g.height,h);return r});a.defineFunction("colorplot",2,function(c){qa();var d=xa(a),f=ya(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return r;var g=a.getImage(g.value,!0),h=Ia(g);b(c,d,f,g.width,g.height,h);return r});a.defineFunction("setpixel",4,function(b){var d;var f=a.evaluateAndVal(b[0]),g;g=void 0===g?null:g;"string"===f.ctype?d=f.value:(console.log("argument is not a string"),d=g);f=Wa(a.evaluateAndVal(b[1]));
g=Wa(a.evaluateAndVal(b[2]));b=Xa(a.evaluateAndVal(b[3]));if(!d)return r;var h=a.getImage(d,!0),h=Ia(h);isFinite(f)&&isFinite(g)&&d&&h&&b&&(h.bindTexture(),d=[b[0],b[1],b[2],1],n.texSubImage2D(n.TEXTURE_2D,0,f,g,1,1,n.RGBA,Ea(),Ca(d)),b=h.canvas.img.getContext("2d"),h=b.createImageData(1,1),h.data.d=d,b.putImageData(h,f,g));return r})});function J(a,b){return{type:"list",length:a,i:b}}function Ta(a){return{type:"constant",value:a}}function Ya(a){return Ta({ctype:"number",value:{real:a,imag:0}})}var A={C:1,A:2,f:3,h:4,V:5,color:6,M:7,T:8,J:9,image:10,N:J(2,3),O:J(3,3),ea:J(4,3),da:function(a){return J(a,3)},ha:function(a){return J(a,4)},sa:J(2,J(2,3)),ta:J(3,J(3,3)),ua:J(4,J(4,3))};Object.freeze(A);
function F(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?F(a.i)+"["+a.length+"]":"constant"===a.type?"const["+JSON.stringify(a.value.value)+"]":JSON.stringify(a)}function K(a){return"list"===a.type&&K(a.i)||I(a,A.f)}function L(a){return"list"===a.type&&L(a.i)||I(a,A.h)}function Za(a){return"constant"===a.type&&I(a,A.A)}function M(a){return"constant"===a.type?z(a.value):a}function G(a){return"list"===a.type?G(a.i)+1:0}
function Ra(a){return void 0!==a.i?Ra(a.i):a}function $a(a,b){return G(a)===G(b)&&(0===G(a)||a.length===b.length&&$a(a.i,b.i))}function N(a){return I(a,A.f)?A.f:I(a,A.h)?A.h:{type:"list",length:a.length,i:N(a.i)}}function ab(a){return I(a,A.h)?A.h:{type:"list",length:a.length,i:ab(a.i)}}function O(a){return a===A.C||a===A.A||a===A.f||a===A.h||"list"===a.type&&a.i===A.f&&1<=a.length&&4>=a.length||"list"===a.type&&"list"===a.i.type&&a.i.i===A.f&&a.length===a.i.length&&2<=a.length&&4>=a.length}
function bb(a){return-1!==[A.C,A.A,A.f,A.h].indexOf(a)}function cb(a,b){return a===b||"constant"===a.type&&"constant"===b.type&&ta(a.value,b.value)||"list"===a.type&&"list"===b.type&&a.length===b.length&&cb(a.i,b.i)}
function I(a,b){return cb(a,b)?!0:a?bb(a)&&bb(b)?a<=b:"constant"===b.type?!1:"constant"===a.type?I(z(a.value),b):b===A.J?I(a,A.h)||I(a,A.N)||I(a,A.M):b===A.M||b===A.T?I(a,A.O):b===A.color?I(a,A.f)||"list"===a.type&&(3===a.length||4===a.length)&&I(a.i,A.f):"list"===a.type&&"list"===b.type&&a.length===b.length?I(a.i,b.i):!1:!1}
function B(a,b){if(!a)return b;if(!b||cb(a,b))return a;"constant"===a.type&&(a=z(a.value));"constant"===b.type&&(b=z(b.value));return bb(a)&&bb(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=B(a.i,b.i))?{type:"list",length:a.length,i:b}:!1}function P(a){return function(b){var c={},d;for(d in a){var f=a[d];c.ga=f[0];if(b.length==c.ga.length&&b.every(function(a){return function(b,c){return I(b,a.ga[c])}}(c)))return{u:c.ga,v:f[1],o:f[2]};c={ga:c.ga}}return!1}}
function db(a){switch(a){case A.A:return P([[[A.C],A.A,Q("int")]]);case A.f:return P([[[A.C],A.f,Q("float")],[[A.A],A.f,Q("float")]]);case A.h:return P([[[A.f],A.h,function(a){return"vec2("+a+", 0.)"}]]);case A.color:return P([[[A.f],A.color,R("float2color")],[[A.O],A.color,function(a){return"vec4("+a+",1.0)"}],[[A.ea],A.color,eb]]);case A.M:return P([[[A.N],A.M,function(a){return"vec3("+a+",1.0)"}],[[A.O],A.M,eb]]);case A.T:return P([[[A.N],A.T,function(a){return"vec3("+a+",1.0)"}],[[A.O],A.T,eb]]);
case A.J:return P([[[A.h],A.J,eb],[[A.N],A.J,eb],[[A.M],A.J,R("dehomogenize")]]);default:if("list"===a.type)return function(b){var c=b[0],d=db(a.i)([c.i]).o;return{u:b,v:a,o:function(b,g,h){return fb(a)(H(a.length).map(function(a){return d([S(c,a)([b],g,h)],g,h)}),g,h)}}}}console.log("no inclusionfunction ->"+F(a)+" implemented yet; using identity...");return function(b){return{u:b,v:a,o:eb}}}
function T(a){switch(a){case A.C:return"bool";case A.A:return"int";case A.f:return"float";case A.h:case A.J:return"vec2";case A.V:return"void";case A.color:return"vec4";case A.M:case A.T:return"vec3"}if("list"===a.type&&a.i===A.f)return 1==a.length?"float":"vec"+a.length;if("list"===a.type&&a.i===A.h)return"cvec"+a.length;if("list"===a.type&&"list"===a.i.type&&a.length===a.i.length&&a.i.i===A.f)switch(a.length){case 2:return"mat2";case 3:return"mat3";case 4:return"mat4"}if("list"===a.type)return"l"+
a.length+"_"+T(a.i);console.error("No WebGL implementation for type "+F(a)+" found")}function gb(a,b){switch(b){case A.C:return T(b)+"("+a.value+")";case A.A:return""+(a.value.real|0);case A.f:return T(b)+"("+a.value.real+")";case A.h:return T(b)+"("+a.value.real+", "+a.value.imag+")";case A.color:return a=a.value.real,"vec4("+a+","+a+","+a+",1.)";default:console.error("Dont know how to paste values of Type "+F(b)+" yet.")}};var U={};function hb(a,b,c){if(!c.mark("includedfunctions",a)){for(var d in U[a])hb(U[a][d],b,c);c.add("includedfunctions",a,function(){return ja[a]})}}function R(a){return function(b,c,d){hb(a,c,d);return Q(a)(b)}};function H(a){return Array.from(Array(a).keys())}function Sa(a){return 4>=a?[a]:5==a?[2,3]:Sa(a-4).concat([4])}function ib(a){var b=Ra(a),c=G(a);return 1==c&&b===A.f?Sa(a.length).map(function(a,b){return{type:A.da(a),name:"a"+b}}):1<=c?H(a.length).map(function(b){return{type:a.i,name:"a"+b}}):[]}function jb(a,b){if(!O(a)){var c=T(a);b.add("structs",c,function(){return"struct "+c+" { "+ib(a).map(function(a){return jb(a.type,b)||T(a.type)+" "+a.name+";"}).join("")+"};"})}}
function kb(a,b,c){if(!O(a)){var d=a.length,f=a.i.length;c.add("functions","mult"+d+"_"+f,function(){return T(A.da(d))+" mult"+d+"_"+f+"("+T(a)+" a, "+T(A.da(f))+" b){return "+lb(d)(H(d).map(function(a){return mb(f)(["a.a"+a,"b"],b,c)}),b,c)+";}"})}}
function nb(a,b,c){if(!O(a)){var d=a.length,f="sum"+T(a);c.add("functions",f,function(){return T(a.i)+" "+f+"("+T(a)+" a){"+(T(a.i)+" res = "+ob(a.i,0)([],b,c)+";\n      "+H(d).map(function(d){return"res = "+pb(a.i)(["res",S(a,d)(["a",d],b,c)],b,c)+";"}).join("\n")+"\n        return res;\n    }")})}}
function qb(a,b,c){var d=a.length,f=a.i.length;c.add("functions","multc"+d+"_"+f,function(){return T(A.ha(d))+" multc"+d+"_"+f+"("+T(a)+" a, "+T(A.ha(f))+" b){\n        return cvec"+d+"("+H(d).map(function(a){return rb(f)(["a.a"+a,"b"],b,c)})+");\n    }\n    "})}function sb(a,b){2<=a&&4>=a||b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+Sa(a).map(function(a,b){return"dot(a.a"+b+",b.a"+b+")"}).join("+")+"; }\n    "})}
function tb(a,b){b.add("functions","cdot"+a,function(){return"vec2 cdot"+a+"(cvec"+a+" a, cvec"+a+" b) {\n      return "+H(a).map(function(a){return"vec2(dot(a.a"+a+",vec2(b.a"+a+".x,-b.a"+a+".y)), dot(a.a"+a+",b.a"+a+".yx))"}).join("+\n")+";\n    }\n    "})}
function ub(a,b,c){var d="add"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"("+T(a)+" a, "+T(a)+" b) {\n    return "+T(a)+"("+ib(a).map(function(a){return T(a.type)+"("+pb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n      }"})}
function vb(a,b,c){var d="sub"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"("+T(a)+" a, "+T(a)+" b) {\n    return "+T(a)+"("+ib(a).map(function(a){return T(a.type)+"("+wb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}function xb(a,b,c){var d="scalarmult"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"(float a, "+T(a)+" b) {\n    return "+T(a)+"("+ib(a).map(function(a){return T(a.type)+"("+yb(a.type)(["a","b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function zb(a,b,c){hb("multc",b,c);var d="cscalarmult"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"(vec2 a, "+T(a)+" b) {\n    return "+T(a)+"("+ib(a).map(function(a){return""+Ab(a.type)(["a","b."+a.name],b,c)}).join(",")+");\n    }"})}
function Bb(a){if(a===A.h)return R("multc");if(O(a))return function(a){return V("*")([a[1],a[0]])};var b=Ra(a);if(I(b,A.f))return function(b,d,f){return kb(a,d,f)||"mult"+a.length+"_"+a.i.length+"("+b.join(",")+")"};if(b===A.h)return function(b,d,f){return qb(a,d,f)||"multc"+a.length+"_"+a.i.length+"("+b.join(",")+")"}}function mb(a){return function(b,c,d){return sb(a,d)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}
function rb(a){return function(b,c,d){return tb(a,d)||"cdot"+a+"("+b.join(",")+")"}}function pb(a){return O(a)?V("+"):function(b,c,d){return ub(a,c,d)||"add"+T(a)+"("+b.join(",")+")"}}function wb(a){return O(a)?V("-"):function(b,c,d){return vb(a,c,d)||"sub"+T(a)+"("+b.join(",")+")"}}function Cb(a){return K(a)&&1==G(a)?function(b,c,d){return mb(a.length)([b[0],lb(a.length)(Array(a.length).fill("1."),c,d)],c,d)}:function(b,c,d){return nb(a,c,d)||"sum"+T(a)+"("+b.join(",")+")"}}
function lb(a){if(2<=a&&4>=a)return function(b){return"vec"+a+"("+b.join(",")+")"};if(1==a)return function(a){return"float("+a.join(",")+")"};var b=0;return function(c,d,f){return jb(A.da(a),f)||"vec"+a+"("+Sa(a).map(function(a){return"vec"+a+"("+H(a).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}function fb(a){return O(a)?function(b){return T(a)+"("+b.join(",")+")"}:1==G(a)&&a.i===A.f?lb(a.length):function(b,c,d){return jb(a,d)||T(a)+"("+b.join(",")+")"}}
function S(a,b){var c=Ra(a);return 1==G(a)&&c===A.f?Db(a.length,b):O(a)?function(a){return"("+a[0]+")["+b+"]"}:function(a){return"("+a[0]+").a"+b}}function ob(a,b){return O(a)?function(){return T(a)+"(float("+b+"))"}:function(c,d,f){return fb(a)+"("+ib(a).map(function(a){return ob(a.type,b)(c,d,f)}).join(",")+")"}}
function Db(a,b){return function(c){if(1==a)return c[0];if(2<=a&&4>=a)return"("+c[0]+")["+b+"]";var d;a:{d=b;var f=Sa(a),g;for(g in f)if(f[g]<=d)d-=f[g];else{d={first:g,second:d};break a}console.error("Accessing index out of range");d=void 0}return"("+c[0]+").a"+d.first+"["+d.second+"]"}}function yb(a){return O(a)?V("*"):function(b,c,d){return xb(a,c,d)||"scalarmult"+T(a)+"("+b.join(",")+")"}}
function Ab(a){return a===A.h?R("multc"):function(b,c,d){return zb(a,c,d)||"cscalarmult"+T(a)+"("+b.join(",")+")"}}function Eb(a,b,c){var d="reverse"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"("+T(a)+" a){"+(T(a.i)+" m;\n")+H(Math.floor(a.length/2)).map(function(d){var g=S(a,d)(["a",d],b,c);d=S(a,a.length-1-d)(["a",a.length-1-d],b,c);return"m = "+g+"; "+g+" = "+d+"; "+d+" = m;"}).join("\n")+"return a;\n      }"})}
function Fb(a){return function(b,c,d){return Eb(a,c,d)||"reverse"+T(a)+"("+b.join(",")+")"}}function Gb(a,b,c){var d="max"+T(a);c.add("functions",d,function(){return T(a.i)+" "+d+"("+T(a)+" a){"+(T(a.i)+" m = "+S(a,a.length-1)(["a",a.length-1],b,c)+";\n")+H(a.length-1).map(function(d){return"m = max(m,"+S(a,d)(["a",d],b,c)+");"}).join("\n")+"return m;\n      }"})}function Hb(a){return function(b,c,d){return Gb(a,c,d)||"max"+T(a)+"("+b.join(",")+")"}}
function Ib(a,b,c){var d="min"+T(a);c.add("functions",d,function(){return T(a.i)+" "+d+"("+T(a)+" a){"+(T(a.i)+" m = "+S(a,a.length-1)(["a",a.length-1],b,c)+";\n")+H(a.length-1).map(function(d){return"m = min(m,"+S(a,d)(["a",d],b,c)+");"}).join("\n")+"return m;\n      }"})}function Jb(a){return function(b,c,d){return Ib(a,c,d)||"min"+T(a)+"("+b.join(",")+")"}};function Kb(a){function b(a,d,h){if(1<d){var l=d/2|0;b(a,l,!h);b(a+l,d-l,h);c(a,d,h)}}function c(a,b,h){if(1<b){var l;for(l=1;l<b;)l<<=1;l>>=1;for(var p=a;p<a+b-l;p++){var q=p,t=p+l;h?d.push([q,t]):d.push([t,q])}c(a,l,h);c(a+l,b-l,h)}}var d=[];b(0,a,!0);return d}
function Lb(a,b,c){var d="sort"+T(a);c.add("functions",d,function(){return T(a)+" "+d+"("+T(a)+" a){"+(T(a.i)+" m;\n")+Kb(a.length).map(function(d){var g=S(a,d[0])(["a",d[0]],b,c);d=S(a,d[1])(["a",d[1]],b,c);return"m = min("+g+","+d+"); "+d+" = max("+g+","+d+"); "+g+" = m;"}).join("\n")+"return a;\n      }"})}function Mb(a){return function(b,c,d){return Lb(a,c,d)||"sort"+T(a)+"("+b.join(",")+")"}};function Q(a){return function(b){return y(a)+"("+b+")"}}function V(a){return function(b){return"("+b.join(a)+")"}}function eb(a){return a}var W={};W.join=P([[A.M,A.M],A.T,Q("cross")]);W.meet=P([[A.T,A.T],A.M,Q("cross")]);
W["if"]=function(a){if(!a.every(function(a){return a}))return!1;if(2===a.length)return{u:a,v:a[1],o:function(a){return"if("+a[0]+") {"+a[1]+";}"}};if(3===a.length){var b=B(a[1],a[2]);return b?{u:[A.C,b,b],v:b,o:function(a){return"("+a[0]+" ? "+a[1]+" : "+a[2]+")"}}:{u:a,v:A.V,o:function(a){return"if("+a[0]+") {"+a[1]+";} else {"+a[2]+";}"}}}return!1};W["="]=function(a){a=B(a[0],a[1]);return{u:a,v:a,o:function(a){return a[0]+" = "+a[1]+";"}}};
W[";"]=function(a){return{u:a,v:a[1]!==A.V?a[1]:a[0],o:function(a){return a[0]+" ; "+a[1]+";"}}};W.repeat=function(a){return 2!=a.length&&3!=a.length||!Za(a[0])?!1:{u:a,v:a[a.length-1],o:function(){return""}}};W.forall=function(a){return 2!=a.length&&3!=a.length||"list"!==M(a[0]).type?!1:{u:a,v:a[a.length-1],o:function(){return""}}};W.apply=function(a){return 2!=a.length&&3!=a.length||"list"!==M(a[0]).type?!1:{u:a,v:J(M(a[0]).length,a[a.length-1]),o:function(){return""}}};
W.sum=function(a){return 1==a.length&&(K(a[0])||L(a[0]))?{u:a,v:a[0].i,o:Cb(a[0])}:!1};W.regional=function(a){return{u:a,v:A.V,o:function(){return""}}};W.sqrt=P([[[A.f],A.h,R("sqrtf")],[[A.h],A.h,R("sqrtc")]]);W.abs=P([[[A.f],A.f,Q("abs")],[[A.h],A.f,Q("length")],[[A.N],A.f,Q("length")],[[A.O],A.f,Q("length")],[[A.ea],A.f,Q("length")]]);W.abs_infix=W.abs;
W.dist=P([[[A.f,A.f],A.f,function(a){return Q("abs")(V("-")(a))}],[[A.h,A.h],A.f,function(a){return Q("length")(V("-")(a))}],[[A.N,A.N],A.f,function(a){return Q("length")(V("-")(a))}],[[A.O,A.O],A.f,function(a){return Q("length")(V("-")(a))}],[[A.ea,A.ea],A.f,function(a){return Q("length")(V("-")(a))}]]);W.dist_infix=W.dist;W.sin=P([[[A.f],A.f,Q("sin")],[[A.h],A.h,R("sinc")]]);W.cos=P([[[A.f],A.f,Q("cos")],[[A.h],A.h,R("cosc")]]);W.tan=P([[[A.f],A.f,Q("tan")],[[A.h],A.h,R("tanc")]]);
W.exp=P([[[A.f],A.f,Q("exp")],[[A.h],A.h,R("expc")]]);W.arctan=P([[[A.f],A.f,Q("atan")],[[A.h],A.h,R("arctanc")]]);W.log=P([[[A.f],A.h,R("logr")],[[A.h],A.h,R("logc")]]);var Nb=[2,3,4].map(function(a){return J(a,A.f)}).concat([2,3,4].map(function(a){return J(a,J(a,A.f))})),Ob=[A.A,A.f,A.h].concat(Nb);W.add=function(a){var b=P(Ob.map(function(a){return[[a,a],a,V("+")]}))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return K(a)||L(a)})&&$a(b,a))return a=B(N(b),N(a)),{u:[a,a],v:a,o:pb(a)}};
W.sub=function(a){var b=P(Ob.map(function(a){return[[a,a],a,V("-")]}).concat(Ob.map(function(a){return[[A.V,a],a,V("-")]})))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return K(a)||L(a)})&&$a(b,a))return a=B(N(b),N(a)),{u:[a,a],v:a,o:wb(a)}};W["+"]=W.add;W["-"]=W.sub;
W._=function(a){var b=M(a[0]);if("list"===b.type&&Za(a[1])){var c=Number(a[1].value.value.real);return 1<=Math.abs(c)&&Math.abs(c)<=b.length?(0<c&&--c,0>c&&(c=b.length+c),{u:a,v:b.i,o:S(b,c)}):{u:a,v:b.i,o:function(){return console.error("try to access "+c+"-th Element of "+b.length+"-list "+JSON.stringify(a[0]))}}}return!1};
W.mult=function(a){var b=P([[[A.A,A.A],A.A,V("*")],[[A.f,A.f],A.f,V("*")],[[A.h,A.f],A.h,V("*")],[[A.f,A.h],A.h,V("*")],[[A.h,A.h],A.h,R("multc")]])(a);if(b)return b;if(2!==a.length)return!1;var b=a[0],c=a[1];if([b,c].every(function(a){return"list"===a.type&&I(a.i,A.f)})&&b.length===c.length)return a=N(b),O(a)?{u:[a,a],v:A.f,o:Q("dot")}:{u:[a,a],v:A.f,o:mb(b.length)};if([b,c].every(function(a){return"list"===a.type&&I(a.i,A.h)})&&b.length===c.length)return a=ab(b),{u:[a,a],v:A.h,o:rb(b.length)};if(K(b)&&
2===G(b)&&K(c)&&1===G(c)&&b.i.length===c.length)return{u:[N(b),N(c)],v:A.da(b.length),o:Bb(N(b))};if(L(b)&&2===G(b)&&L(c)&&1===G(c)&&b.i.length===c.length)return{u:[ab(b),ab(c)],v:A.ha(b.length),o:Bb(ab(b))};for(b={H:0};2>b.H;b={Z:b.Z,H:b.H,fa:b.fa},b.H++){if(I(a[0^b.H],A.f)&&(K(a[1^b.H])||L(a[1^b.H])))return b.Z=N(a[1^b.H]),{u:b.H?[b.Z,A.f]:[A.f,b.Z],v:b.Z,o:function(a){return function(b,c,h){return yb(a.Z)([b[0^a.H],b[1^a.H]],c,h)}}(b)};if(I(a[0^b.H],A.h)&&L(a[1^b.H]))return b.fa=ab(a[1^b.H]),{u:b.H?
[b.fa,A.h]:[A.h,b.fa],v:b.fa,o:function(a){return function(b,c,h){return Ab(a.fa)([b[0^a.H],b[1^a.H]],c,h)}}(b)}}};W["*"]=W.mult;W.div=function(a){var b=P([[[A.f,A.f],A.f,V("/")],[[A.f,A.h],A.h,R("divfc")],[[A.h,A.f],A.h,V("/")],[[A.h,A.h],A.h,R("divc")]])(a);return b?b:I(a[1],A.f)&&L(a[0])&&(a=N(a[0]),O(a))?{u:[a,A.f],v:a,o:V("/")}:!1};W["/"]=W.div;W.re=P([[[A.h],A.f,R("realc")]]);W.im=P([[[A.h],A.f,R("imagc")]]);W.floor=P([[[A.f],A.A,function(a){return"int(floor("+a+"))"}],[[A.h],A.h,Q("floor")]]);
W.round=P([[[A.f],A.A,function(a){return"int(floor("+a+"+.5))"}],[[A.h],A.h,function(a){return"floor("+a+"+vec2(.5))"}]]);W.ceil=P([[[A.f],A.A,function(a){return"int(ceil("+a+"))"}],[[A.h],A.h,Q("ceil")]]);W.mod=P([[[A.A,A.A],A.A,function(a,b){return"int("+Q("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[A.f,A.f],A.f,Q("mod")],[[A.h,A.h],A.h,R("mod")]]);
W.random=P([[[],A.f,R("random")],[[A.f],A.f,function(a,b){return R("random")([],b)+"*"+a[0]}],[[A.h],A.h,function(a,b){return"vec2("+R("random")([],b)+","+R("random")([],b)+")*"+a[0]}]]);W.arctan2=P([[[A.f,A.f],A.f,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[A.h,A.h],A.h,R("arctan2c")],[[A.h],A.f,R("arctan2vec2")],[[A.N],A.f,R("arctan2vec2")],[[A.ha(2)],A.h,R("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){W[a]=P([[[A.f],A.O,R(a)]])});W.grey=W.gray;
W.min=function(a){var b=P([[[A.f,A.f],A.f,Q("min")]])(a);if(b)return b;if(1===a.length&&1===G(a[0])&&K(a[0]))return{u:a,v:a[0].i,o:Jb(a[0])}};W.max=function(a){var b=P([[[A.A,A.A],A.A,Q("max")],[[A.f,A.f],A.f,Q("max")]])(a);if(b)return b;if(1===a.length&&1===G(a[0])&&K(a[0]))return{u:a,v:a[0].i,o:Hb(a[0])}};W.complex=P([[[A.N],A.h,eb]]);
function Pb(a,b){if(!(1>=a))if(2==a)b.add("functions","raise2",function(){return"float raise2(float a) { return a*a; }"});else{Pb(2,b);var c=function(a,b){return 1==b?a:b&1?c(a,b-1)+"*a":"raise2("+c(a,b/2)+")"},d="raise"+a;b.add("functions",d,function(){return"float "+d+"(float a) { return "+c("a",a)+";}"})}}function Qb(a){return function(b,c,d){return 0==a?"1.":1==a?b[0]:Pb(a,d)||"raise"+a+"("+b[0]+")"}}
W.pow=function(a){if(Za(a[1])&&I(a[0],A.f)){var b=Number(a[1].value.value.real);if(0<=b)return{u:[A.f,a[1]],v:A.f,o:Qb(b)}}return P([[[A.f,A.A],A.f,R("powi")],[[A.h,A.h],A.h,R("powc")]])(a)};W["^"]=W.pow;W.re=P([[[A.h],A.f,function(a){return"("+a+").x"}]]);W.conjugate=P([[[A.h],A.h,R("conjugate")]]);W.im=P([[[A.h],A.f,function(a){return"("+a+").y"}]]);W.genList=function(a){var b=a.length;if(0<b){var c=!1,d;for(d in a)c=B(c,a[d]);if(c)return a=J(b,c),{u:Array(b).fill(c),v:a,o:fb(a)}}return!1};
W["&"]=P([[[A.C,A.C],A.C,V("&&")]]);W["%"]=P([[[A.C,A.C],A.C,V("||")]]);"> < >= <= == !=".split(" ").forEach(function(a){W[a]=P([[[A.A,A.A],A.C,V(a)],[[A.f,A.f],A.C,V(a)]])});W["!"]=P([[[A.C],A.C,Q("!")],[[A.V,A.C],A.C,function(a){return Q("!")([a[1]])}]]);W.not=W["!"];W.imagergb=P([[[A.image,A.J],A.O,Rb],[[A.J,A.J,A.image,A.J],A.O,Sb]]);W.imagergba=P([[[A.image,A.J],A.ea,Tb],[[A.J,A.J,A.image,A.J],A.ea,Ub]]);W.reverse=function(a){return 1===a.length&&"list"===a[0].type?{u:a,v:a[0],o:Fb(a[0])}:!1};
W.sort=function(a){return 1===a.length&&1===G(a[0])&&K(a[0])?{u:a,v:a[0],o:Mb(a[0])}:!1};Object.freeze(W);U.powc=["expc","multc","logc"];U.sqrtc=["expc","multc","logc"];U.arccosc=["multc","negc","sqrtc","addc","logc"];U.arcsinc=["multc","negc","sqrtc","addc","logc"];U.tanc=["sinc","cosc","divc"];U.arctanc=["logc","addc","multc","subc"];U.arctan2c=["logc","divc","sqrtc","multc"];U.arctan2vec2c=["arctan2c"];U.hue=["hsv2rgb"];Object.freeze(U);function Pa(a){this.j={};this.D={};this.l={};this.P=0;this.s={};this.B=a;this.F={}}Pa.prototype.add=function(a,b,c){this.mark(a,b);this.l[a].ka[b]||(this.l[a].ka[b]=c(),this.l[a].ja[b]=!0,this.l[a].order.push(b))};Pa.prototype.mark=function(a,b){this.l[a]||(this.l[a]={order:[],ja:{},ka:{}});var c=this.l[a].ja[b]||!1;this.l[a].ja[b]=!0;return c};function Vb(a,b){return a.l[b]?a.l[b].order.map(function(c){return a.l[b].ka[c]}).join("\n"):"\n"}
function Wb(a,b,c,d){if(cb(c,d))return b;if(I(c,d)){if("constant"===c.type)return gb(c.value,d);var f=db(d)([c]);if(!f)return console.error("cannot find an implementation for "+F(c)+" -> "+F(d)+", using identity"),b;d=f.o;return d(Wb(a,b,c,f.u[0]),{},a)}console.error(F(c)+" is no subtype of "+F(d)+" (trying to cast the term "+b+")");return b}function X(a,b,c){a.j[b]||(a.j[b]={});a.j[b].R||(a.j[b].R=[]);a.j[b].w||(a.j[b].w=!1);a.hasOwnProperty("global")||(a.j[b].global=c)}
function Xb(a,b){var c=b.I;if(b.isuniform)return a.D[b.uvariable].type;if("variable"===b.ctype)return b=b.name,b=c[b]||b,a.j[b].w;if("function"===b.ctype&&a.s.hasOwnProperty(b.oper))return a.j[c[b.oper]].w;if("number"===b.ctype)return Ta(b);if("void"===b.ctype)return A.V;if("field"===b.ctype){a=M(Y(a,b.obj));if("list"===a.type)return a.i;if(!a)return!1}else{if("string"===b.ctype)return A.image;if("function"===b.ctype||"infix"===b.ctype){for(var c=Array(b.args.length),d=!0,f=0;f<b.args.length;f++)c[f]=
Y(a,b.args[f]),d&="constant"===c[f].type;if(d&&b.impl)return b={ctype:b.ctype,oper:b.oper,impl:b.impl,args:c.map(function(a){return a.value})},b=a.B.evaluateAndVal(b),Ta(b);a=y(b.oper);d=W[a]?W[a](c):!1;if(!d&&c.every(function(a){return Ra(a)}))throw console.error("Could not find an implementation for "+a+" with args ("+c.map(F).join(", ")+")"),console.log(b),"error";return d?d.v:!1}}console.error("Don't know how to compute type of");console.log(b);return!1}
function Y(a,b){if(!b.la||!b.P||a.P>b.P)b.la=Xb(a,b),b.P=a.P;return b.la}
function Yb(a,b,c){function d(a,b,c){var d={},f;for(f in a)d[f]=a[f];a=D();X(l,a,!1);g[a].w=c;g[a].pa=!0;d[b]=a;return d}function f(a,b,c,u){a.I=b;for(var x in a.args){var C=u||"repeat$2"===a.oper&&0==x||"repeat$3"===a.oper&&0==x||"_"===a.oper&&1==x,ka=b;-1!=["repeat","forall","apply"].indexOf(y(a.oper))&&(1==x?ka="repeat$2"===a.oper?d(b,"#",A.A):"repeat$3"===a.oper?d(b,a.args[1].name,A.A):"forall$2"===a.oper||"apply$2"===a.oper?d(b,"#",!1):"forall$3"===a.oper||"apply$3"===a.oper?d(b,a.args[1].name,
!1):b:2==x&&(ka=a.args[1].I));f(a.args[x],ka,c,C)}"field"===a.ctype&&f(a.obj,b,c,u);"variable"===a.ctype&&(x=a.name,x=b[x]||x,u&&l.j[x]&&(l.j[x].$=!0));if("="===a.oper)u=a.args[0].name,u=b[u]||u,X(l,u,!0),g[u].R.push(a.args[1]);else if(a.oper&&"regional"===y(a.oper)&&"global"!=c)for(var la in a.args){u=a.args[la].name;var ma=D();b[u]=ma;h[c].j||(h[c].j=[]);h[c].j.push(ma);X(l,ma,!1)}else if("forall$2"===a.oper||"apply$2"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)g[2===a.args.length?a.args[1].I["#"]:
a.args[2].I[a.args[1].name]].R.push({ctype:"infix",oper:"_",args:[a.args[0],{ctype:"number",value:{real:1,imag:0}}],I:a.args[0].I});else if("function"===a.ctype&&h.hasOwnProperty(a.oper)){c=a.oper;la=c.replace("$","_");X(l,la,!1);b[c]=la;b={};for(ma in h[c].arglist)x=h[c].arglist[ma].name,C=la+"_"+x,b[x]=C,X(l,C,!1),g[C].R.push(a.args[ma]);h[c].ra||(h[c].ra=!0,f(h[c].body,b,c,u),g[la].R.push(h[c].body))}}var g=a.j,h=a.s,l=a;f(b,c,"global",!1)}
function Zb(a,b){function c(a){if(a.hasOwnProperty("dependsOnPixel"))return a.dependsOnPixel;if("variable"===a.ctype){var b=a.name,b=a.I[b]||b;return h[b]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}b=["random","verbatimglsl"];if("function"===a.ctype&&-1!=b.indexOf(y(a.oper)))return a.dependsOnPixel=!0;if("repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper)return c(a.args[1])?(h[a.args[1].I["#"]]=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;if("repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===
a.oper)return c(a.args[2])?(h[a.args[2].I[a.args[1].name]]=!0,a.args[1].dependsOnPixel=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;for(var d in a.args)if(c(a.args[d]))return a.dependsOnPixel=!0;return"function"===a.ctype&&g.hasOwnProperty(a.oper)&&c(g[a.oper].body)?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj):a.dependsOnPixel=!1}function d(a,b){if(c(a)){for(var f in a.args)d(a.args[f],b||"repeat$2"===a.oper&&0==f||"repeat$3"===a.oper&&0==f||"_"===a.oper&&1==f);"field"===a.ctype&&
d(a.obj,b);"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(a=a.oper,p.hasOwnProperty(a)||(p[a]=!0,d(g[a].body,b)))}else if("boolean"!==a.ctype&&"number"!==a.ctype&&"void"!==a.ctype){".."===a.oper&&(b=!0);f=!1;var h,l;for(l in q)!f&&ta(a,q[l].W)&&(f=!0,h=l);f||(h=D(),q[h]={W:a,type:!1,$:b});q[h].$=q[h].$||b;a.isuniform=!0;a.uvariable=h}}var f=a.j,g=a.s,h={cgl_pixel:!0,"cgl_pixel.x":!0,"cgl_pixel.y":!0},l;for(l in f)if(1<=f[l].R.length||f[l].pa)h[l]=!0;c(b);var p={"":!0},q=a.D;d(b,!1)}
function $b(a,b){if("function"===b.ctype&&!a.s.hasOwnProperty(b.oper)&&null!==a.B.getMyfunction(b.oper)){var c=b.oper;a.s[c]=sa(a.B.getMyfunction(c));$b(a,a.s[c].body)}for(var d in b.args)$b(a,b.args[d])}
function ac(a,b){function c(a){var b={},c;for(c in a)b[c]=a[c];return b}function d(a,b){"repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper?(b=c(b),b["#"]=!0):"repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper?(b=c(b),b[a.args[1].name]=!0):"="===a.oper&&(b[a.args[0].name]=!0);for(var f in a.args)d(a.args[f],b);"field"===a.ctype&&d(a.obj,b);"variable"===a.ctype&&(a=a.name,b[a]||(g[a]=!0))}var f={},g={};d(b,{});X(a,"cgl_pixel",!1);a.j.cgl_pixel.w=A.N;if(1==Object.keys(g).length)f[Object.keys(g)[0]]=
"cgl_pixel";else if(g["#"])f["#"]="cgl_pixel";else if(g.x&&g.y)X(a,"cgl_pixel.x",!1),a.j["cgl_pixel.x"].w=A.f,f.x="cgl_pixel.x",X(a,"cgl_pixel.y",!1),a.j["cgl_pixel.y"].w=A.f,f.y="cgl_pixel.y";else{b=[];for(var h in g)a.B.nada==a.B.evaluateAndVal({ctype:"variable",name:h})&&b.push(h);1==b.length?f[b[0]]="cgl_pixel":g.p?f.p="cgl_pixel":g.z&&(f.z="cgl_pixel")}"cgl_pixel"===f.z&&(a.j.cgl_pixel.w=A.h);return f}
function Z(a,b,c){var d=Y(a,b);if(b.isuniform)return b=b.uvariable,c?{code:"",m:"constant"===d.type?gb(d.value,M(d)):b}:{code:""};if(";"===b.oper){for(var d={m:""},f="",g=b.args.length-1,h=g;0<=h;h--)"void"===b.args[h].ctype&&(g=h-1);for(h=0;h<=g;h++)d=Z(a,b.args[h],c&&h===g),f+=d.code;return c?{code:f,m:d.m}:{code:f}}if("constant"===d.type)return c?{m:gb(d.value,M(d)),code:""}:{code:""};if("="===b.oper)return d=Z(a,b.args[1],!0),b=Z(a,b.args[0],!0).m+" = "+Wb(a,d.m,Y(a,b.args[1]),Y(a,b.args[0])),
c?{code:d.code,m:b}:{code:d.code+b+";\n"};if("repeat$2"===b.oper||"repeat$3"===b.oper){f=Z(a,b.args[0],!0);if("constant"!==Y(a,b.args[0]).type)return console.error("repeat possible only for fixed constant number in GLSL"),!1;d="repeat$2"===b.oper?b.args[1].I["#"]:b.args[2].I[b.args[1].name];f=Number(f.m);g="";if("constant"===a.j[d].w.type)for(h=1;h<=f;h++){a.j[d].w=Ya(h);a.P++;var l=Z(a,b.args["repeat$2"===b.oper?1:2],h===f&&c),g=g+l.code;if(h===f&&c)return{code:g,m:l.m}}else if(h="",l=Z(a,b.args["repeat$2"===
b.oper?1:2],c),b=Y(a,b.args["repeat$2"===b.oper?1:2]),c&&(h=D(),a.j[h]||(X(a,h,!0),a.j[h].w=b)),g=g+("for(int "+d+"=1; "+d+" <= "+f+"; "+d+"++) {\n")+l.code,c&&(g+=h+" = "+l.m+";\n"),g+="}\n",c)return{code:g,m:h};return{code:g}}if("forall$2"===b.oper||"forall$3"===b.oper||"apply$2"===b.oper||"apply$3"===b.oper){var p=Y(a,b.args[0]);if("list"!==p.type&&("constant"!==p.type||"list"!==p.value.ctype))return console.error(b.oper+" only possible for lists"),!1;var f=p.length||p.value.value.length,h=2===
b.args.length?b.args[1].I["#"]:b.args[2].I[b.args[1].name],q=a.j[h].w,t=l="";c&&(t=D(),l+=T(d)+" "+t+";\n");"list"===d.type&&jb(d,a);if("constant"===a.j[h].w.type||"constant"===p.type)for(p=a.B.evaluateAndVal(b.args[0]),q=0;q<f;q++)a.j[h].w=Ta(p.value[q]),a.P++,g=Z(a,b.args[2===b.args.length?1:2],c),l+=g.code,"forall$2"===b.oper||"forall$3"===b.oper?q+1===f&&c&&(l+=t+" = "+g.m+";\n"):c&&(l+=S(d,q)([t],[],a)+" = "+g.m+";\n");else{var g=Z(a,b.args[2===b.args.length?1:2],c),u=Z(a,b.args[0],!0),l=l+u.code,
x=u.m;!a.j[x]&&!a.D[x]&&2<=p.length&&(x=D(),l+=T(p)+" "+x+" = "+u.m+";\n");a.j[h].global=!0;for(u=0;u<f;u++)l+=h+" = "+S(p,u)([x],[],a)+";\n",l+=g.code,c&&("forall$2"===b.oper||"forall$3"===b.oper?u===f-1&&(l+=t+" = "+g.m+";\n"):l+=S(d,u)([t],[],a)+" = "+g.m+";\n");"list"===q.type&&jb(q,a)}return c?{code:l,m:t}:{code:l}}if("if$2"===b.oper||"if$3"===b.oper){l=Z(a,b.args[0],!0);f=Y(a,b.args[0]);h=g="";t=Z(a,b.args[1],c);c&&(h=D(),a.j[h]||(X(a,h,!0),a.j[h].w=d));"constant"!=f.type&&(g+=l.code,g+="if("+
l.m+") {\n");if("constant"!=f.type||"constant"==f.type&&f.value.value)g+=t.code,c&&(g+=h+" = "+Wb(a,t.m,Y(a,b.args[1]),d)+";\n");"if$3"===b.oper&&(l=Z(a,b.args[2],c),"constant"!=f.type&&(g+="} else {\n"),"constant"!=f.type||"constant"==f.type&&!f.value.value)&&(g+=l.code,c&&(g+=h+" = "+Wb(a,l.m,Y(a,b.args[2]),d)+";\n"));"constant"!=f.type&&(g+="}\n");return c?{code:g,m:h}:{code:g}}if("function"===b.ctype||"infix"===b.ctype){l=b.oper;if("verbatimglsl"===y(l))return b=a.B.evaluateAndVal(b.args[0]).value,
c?{m:b,code:""}:{code:b};d=b.args.map(function(b){return Z(a,b,!0)});f=b.args.map(function(b){return Y(a,b)});if(a.s.hasOwnProperty(l))for(h=bc(a,l),g=Array(d.length),t=0;t<d.length;t++)g[t]=a.j[a.s[l].body.I[a.s[l].arglist[t].name]].w;else{l=y(l);if("regional"===l)return c?{m:"",code:""}:{code:""};h=W[l](f);if(!h)return console.error("Could not find an implementation for "+l+"("+f.map(F).join(", ")+").\nReturning empty code"),c?{m:"",code:""}:{code:""};g=h.u;h=h.o}l="";t=Array(d.length);for(p=0;p<
d.length;p++)l+=d[p].code,t[p]=Wb(a,d[p].m,f[p],g[p]);b=h(t,b.modifs,a);return c?{m:b,code:l}:{code:l+b+";\n"}}if("variable"===b.ctype)return d=b.name,d=b.I[d]||d,c?{m:d,code:""}:{code:d+";\n"};if("void"===b.ctype)return c?{m:"",code:""}:{code:""};if("field"===b.ctype&&(d={x:0,y:1,z:2,r:0,g:1,b:2,a:3}[b.key],void 0!=d))return b=S(Y(a,b.obj),d)([Z(a,b.obj,!0).m],null,a),c?{m:b,code:""}:{code:b+";\n"};console.error("dont know how to this.compile "+JSON.stringify(b))}
function bc(a,b){cc(a,b,a.s[b].arglist.length);return Q(b.replace("$","_"))}
function cc(a,b,c){if(!a.mark("compiledfunctions",b)){for(var d=a.s[b],f=b.replace("$","_"),g=d.body.I,h=Array(c),l=0;l<c;l++)h[l]=d.arglist[l].name;c=a.j[f].w===A.V;var p=T(a.j[f].w)+" "+f+"("+h.map(function(b){return T(a.j[g[b]].w)+" "+g[b]}).join(", ")+"){\n",q;for(q in d.j)h=d.j[q],p+=T(a.j[h].w)+" "+h+";\n";q=Z(a,d.body,!c);d=Y(a,d.body);p+=q.code;c||(p+="return "+Wb(a,q.m,d,a.j[f].w)+";\n");p+="}\n";a.add("compiledfunctions",b,function(){return p})}}
function Oa(a,b){ua=0;var c=b=sa(b);$b(a,c);Yb(a,c,ac(a,c));Zb(a,c);for(var d in a.D){c=a.B.evaluateAndVal(a.D[d].W);if(!c.ctype||"undefined"===c.ctype){console.error("can not evaluate:");console.log(a.D[d].W);break}a.D[d].type=a.D[d].$?Ta(c):z(c)}d=!0;for(var f in a.j)a.j[f].w=a.j[f].w||!1,a.j[f].$&&(a.j[f].w=Ya(1),a.P++);for(;d;){d=!1;for(var g in a.j)if(!a.j[g].$)for(var h in a.j[g].R){f=M(Y(a,a.j[g].R[h]));var l=c=a.j[g].w||!1;f&&(c?I(f,c)?l=c:l=B(c,f):l=f,l&&l!==c&&(a.j[g].w=l,a.P++,d=!0))}}for(var p in a.D)"list"===
a.D[p].type.type&&jb(a.D[p].type,a);for(var q in a.j)"list"===a.j[q].w.type&&jb(a.j[q].w,a);g=Z(a,b,!0);h=Y(a,b);b=Wb(a,g.m,h,A.color);I(h,A.color)||console.error("expression does not generate a color");h=Vb(a,"structs");h+=Vb(a,"uniforms");p=[];for(var t in a.D)"constant"!=a.D[t].type.type&&a.D[t].type!=A.image&&p.push("uniform "+T(a.D[t].type)+" "+t+";");h+=p.join("\n");t="";for(var u in a.F)for(var x in a.F[u])t+=a.F[u][x].code+"\n";h=h+t+Vb(a,"includedfunctions");h+=Vb(a,"functions");for(var C in a.j)a.j[C].w&&
a.j[C].global&&(h+=T(a.j[C].w)+" "+C+";\n");h+=Vb(a,"compiledfunctions");h+="void main(void) {\n"+g.code+"gl_FragColor = "+b+";\n}\n";console.log(h);u={};if(a.l.compiledfunctions)for(var ka in a.l.compiledfunctions.ja)u[ka]=a.B.getMyfunction(ka).generation;return{code:h,D:a.D,F:a.F,ia:u}};function dc(a,b,c,d){this.W=b;this.B=d;this.X=c;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nuniform bool _repeat"+a+";\nuniform bool _mipmap"+a+";\nvec4 _imagergba"+a+" (vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  if(_repeat"+a+") p = mod(p, vec2(1.));\n  if(_repeat"+a+" && _mipmap"+a+") {\n    vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;\n  }\n  if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n    return texture2D(_sampler"+a+", p*_cropfact"+a+");\n  else\n    return vec4(0.);\n  }"}function Va(a,b){var c=a.B.evaluateAndVal(a.W).value;a="string"===typeof c?a.B.getImage(c,!0):c;return null==a?(console.error("Could not find image "+c+"."),r):Ha(a,b)}
function ec(a,b,c){c.F.hasOwnProperty(a)||(c.F[a]=[]);var d=c.F[a].length,f;for(f in c.F[a])if(d==c.F[a].length){var g=c.F[a][f].X,h=!0,l;for(l in["interpolation","mipmap","repeat"])h&&(ta(g,b)||(h=!1));h&&(d=f)}f=a+"_"+d;d==c.F[a].length&&c.F[a].push(new dc(f,c.D[a].W,b,c.B));return f}function Ub(a,b,c){return["_imagergba",ec(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function Sb(a,b,c){return["(_imagergba",ec(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function Tb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["_imagergba",ec(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],")"].join("")}function Rb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["(_imagergba",ec(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],").rgb)"].join("")};function fc(a){var b;b=b?b:null;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Xa(a){var b;b=b?b:[.5,.5,.5];if("number"===a.ctype){var c=gc(a);if(!isNaN(c))return[c,c,c]}a=fc(a);return a?3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return gc(a)}):b}
function Wa(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function gc(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function ra(a){this.l=a}ra.prototype.toString=function(){return this.l};
function Ka(a,b){var c=n;this.l=c.createProgram();c.l&&(a="#version 300 es\n"+a.replace(/attribute/g,"in").replace(/varying/g,"out"),b="#version 300 es\n"+b.replace(/varying/g,"in").replace(/gl_FragColor/g,"FragColor").replace(/texture2D/g,"texture").replace(/precision highp float;/g,"precision highp float;\n#define webgl2 true\nout vec4 FragColor;"));this.Z=hc(this,c,c.VERTEX_SHADER,a);hc(this,c,c.FRAGMENT_SHADER,b);a=this.l;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new ra("Error linking shader:\n"+
c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new ra("Error validating shader:\n"+c.getProgramInfoLog(a));var d=this.l,f,g,h,l={},p,q,t,u;b=c.getProgramParameter(d,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a)if(f=c.getActiveUniform(d,a))if(g=f.name.replace(/\]/g,"")){for(p=l;h=/[.\[]/.exec(g);)q=g.substr(0,h.index),p.hasOwnProperty(q)?p=p[q]:"."===h[0]?p=p[q]={}:p=p[q]=[],g=g.substr(h.index+1);if(1<f.size){h=f.size;u=Array(h);for(q=0;q<h;++q)t=f.name+"["+
q+"]",t=ic(this,c,t,f),u[q]=t;p[g]=u}else t=ic(this,c,f.name,f),p[g]=t}this.s=l}function hc(a,b,c,d){c=b.createShader(c);b.shaderSource(c,d);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(d.split("\n")),new ra("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.l,c);return c}
function ic(a,b,c,d){a=b.getUniformLocation(a.l,c);switch(d.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new ra("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


